import { Brand } from "@/enums/brand.enum";
import { ProductType } from "@/enums/productType.enum";
import { Product } from "@/interfaces/product.interface";

export const dummyProducts: Product[] = [
    {
    id: '1',
    title: '24K Diamond Ring',
    name: 'Solitaire Shine',
    description: 'Beautiful solitaire ring.',
    productType: ProductType.Ring,
    givenPrice: 25000,
    discountedPrice: 20000,
    brand: Brand.Kalyan,
    tags: ['new', 'diamond'],
    thumbnailUrls: ['https://images.unsplash.com/photo-1605100804763-eb2fc645a382?q=80&w=400'],
    isNew: true,
    rating: 4,
  },
  {
    id: '2',
    title: 'Gold Plated Ring',
    name: 'Daily Wear',
    description: 'Perfect for daily use.',
    productType: ProductType.Ring,
    givenPrice: 12000,
    discountedPrice: 9500,
    brand: Brand.Malabar,
    tags: ['gold', 'sale'],
    thumbnailUrls: ['https://images.unsplash.com/photo-1626784215021-2e39ccf971cd?q=80&w=400'],
    isNew: true,
    rating: 5,
  },
  {
    id: '3',
    title: 'Emerald Cut Ring',
    name: 'Green Glory',
    description: 'Stunning emerald.',
    productType: ProductType.Ring,
    givenPrice: 45000,
    discountedPrice: 38000,
    brand: Brand.Tanishq,
    tags: ['gemstone'],
    thumbnailUrls: ['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=400'],
    isNew: false,
    rating: 4,
  },
  {
    id: '4',
    title: 'Platinum Band',
    name: 'Classic Band',
    description: 'Timeless platinum.',
    productType: ProductType.Ring,
    givenPrice: 30000,
    discountedPrice: 28500,
    brand: Brand.CaratLane,
    tags: ['platinum'],
    thumbnailUrls: ['https://images.unsplash.com/photo-1589674781759-c21c37956a44?q=80&w=400'],
    isNew: true,
    rating: 3,
  },
  {
    id: '5',
    title: 'Rose Gold Ring',
    name: 'Rose Petal',
    description: 'Delicate rose gold.',
    productType: ProductType.Ring,
    givenPrice: 18000,
    discountedPrice: 15000,
    brand: Brand.Bluestone,
    tags: ['rosegold'],
    thumbnailUrls: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=400'],
    isNew: false,
    rating: 5,
  },
  {
    id: '6',
    title: 'Silver Band',
    name: 'Simple Silver',
    description: 'Minimalist.',
    productType: ProductType.Ring,
    givenPrice: 5000,
    discountedPrice: 4500,
    brand: Brand.CaratLane,
    tags: ['silver'],
    thumbnailUrls: ['https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=400'],
    isNew: false,
    rating: 4,
  },
  {
    id: "prod-001",
    name: "Classic Gold Necklace",
    title: "Classic Gold Necklace",
    description: "Elegant 22K gold necklace with intricate design.",
    productType: ProductType.Necklace,
    givenPrice: 1200,
    discountedPrice: 999,
    brand: Brand.KalyanJewellers,
    tags: ["gold", "necklace", "classic", "22K"],
    isNew: true,
    rating: 5,
    thumbnailUrls: [
      "https://example.com/images/necklace-001-1.jpg",
      "https://example.com/images/necklace-001-2.jpg",
    ],
  },
  {
    id: "prod-002",
    name: "Diamond Stud Earrings",
    title: "Diamond Stud Earrings",
    description: "Timeless diamond studs set in 18K white gold.",
    productType: ProductType.DiamondStone,
    givenPrice: 800,
    discountedPrice: 749,
    brand: Brand.Tanishq,
    tags: ["diamond", "earrings", "stud", "white-gold"],
    thumbnailUrls: [
      "https://example.com/images/earrings-002-1.jpg",
      "https://example.com/images/earrings-002-2.jpg",
    ],
  },
  {
    id: "prod-003",
    name: "Silver Charm Bracelet",
    title: "Silver Charm Bracelet",
    description: "Sterling silver bracelet with customizable charms.",
    productType: ProductType.Bracelet,
    givenPrice: 250,
    discountedPrice: 199,
    brand: Brand.KalyanJewellers,
    tags: ["silver", "bracelet", "charms", "sterling"],
    thumbnailUrls: [
      "https://example.com/images/bracelet-003-1.jpg",
    ],
  },
  {
    id: "prod-004",
    name: "Ruby Ring",
    title: "Ruby Ring",
    description: "Statement ring featuring a natural ruby centerpiece.",
    productType: ProductType.Ring,
    givenPrice: 950,
    discountedPrice: 875,
    brand: Brand.Tanishq,
    tags: ["ruby", "ring", "gemstone", "statement"],
    thumbnailUrls: [
      "https://example.com/images/ring-004-1.jpg",
      "https://example.com/images/ring-004-2.jpg",
    ],
  },
  {
    id: "prod-005",
    name: "Ruby Earring",
    title: "Ruby Earring",
    description: "Statement Earring featuring a natural ruby centerpiece.",
    productType: ProductType.Earring,
    givenPrice: 950,
    discountedPrice: 875,
    brand: Brand.Tanishq,
    tags: ["ruby", "ring", "gemstone", "statement"],
    thumbnailUrls: [
      "https://example.com/images/ring-004-1.jpg",
      "https://example.com/images/ring-004-2.jpg",
    ],
  },
  {
    id: "prod-006",
    name: "Diamond Necklace Gift",
    title: "Diamond Necklace Gift",
    description: "Timeless diamond necklace gift set in 18K white gold.",
    productType: ProductType.Gift,
    givenPrice: 800,
    discountedPrice: 749,
    brand: Brand.CaratLane,
    tags: ["diamond", "earrings", "stud", "white-gold"],
    thumbnailUrls: [
      "https://example.com/images/earrings-002-1.jpg",
      "https://example.com/images/earrings-002-2.jpg",
    ],
  },

  {
    id: "prod-007",
    name: "Gold Necklace",
    title: "Diamond Necklace ",
    description: "Timeless gold necklace set in 18K white gold.",
    productType: ProductType.Gold,
    givenPrice: 800,
    discountedPrice: 749,
    brand: Brand.CaratLane,
    tags: ["diamond", "earrings", "stud", "white-gold"],
    thumbnailUrls: [
      "https://example.com/images/earrings-002-1.jpg",
      "https://example.com/images/earrings-002-2.jpg",
    ],
  },
];