import { assetUrl } from "@/constants/assets";
import { Brand } from "@/enums/brand.enum";
import { ProductType } from "@/enums/productType.enum";
import { Product } from "@/interfaces/product.interface";

export const dummyProducts: Product[] = [
    {
    id: '1',
    title: '24K Diamond Ring',
    name: 'Solitaire Shine',
    description: 'Beautiful solitaire ring.',
    productType: ProductType.Ring,
    givenPrice: 25000,
    discountedPrice: 20000,
    brand: Brand.Kalyan,
    tags: ['new', 'diamond'],
    thumbnailUrls: [assetUrl("mock.product.solitaireShine.image1")],
    isNew: true,
    rating: 4,
  },
  {
    id: '2',
    title: 'Gold Plated Ring',
    name: 'Daily Wear',
    description: 'Perfect for daily use.',
    productType: ProductType.Ring,
    givenPrice: 12000,
    discountedPrice: 9500,
    brand: Brand.Malabar,
    tags: ['gold', 'sale'],
    thumbnailUrls: [assetUrl("mock.product.dailyWearRing.image1")],
    isNew: true,
    rating: 5,
  },
  {
    id: '3',
    title: 'Emerald Cut Ring',
    name: 'Green Glory',
    description: 'Stunning emerald.',
    productType: ProductType.Ring,
    givenPrice: 45000,
    discountedPrice: 38000,
    brand: Brand.Tanishq,
    tags: ['gemstone'],
    thumbnailUrls: [assetUrl("mock.product.emeraldRing.image1")],
    isNew: false,
    rating: 4,
  },
  {
    id: '4',
    title: 'Platinum Band',
    name: 'Classic Band',
    description: 'Timeless platinum.',
    productType: ProductType.Ring,
    givenPrice: 30000,
    discountedPrice: 28500,
    brand: Brand.CaratLane,
    tags: ['platinum'],
    thumbnailUrls: [assetUrl("mock.product.platinumBand.image1")],
    isNew: true,
    rating: 3,
  },
  {
    id: '5',
    title: 'Rose Gold Ring',
    name: 'Rose Petal',
    description: 'Delicate rose gold.',
    productType: ProductType.Ring,
    givenPrice: 18000,
    discountedPrice: 15000,
    brand: Brand.Bluestone,
    tags: ['rosegold'],
    thumbnailUrls: [assetUrl("mock.product.roseGoldRing.image1")],
    isNew: false,
    rating: 5,
  },
  {
    id: '6',
    title: 'Silver Band',
    name: 'Simple Silver',
    description: 'Minimalist.',
    productType: ProductType.Ring,
    givenPrice: 5000,
    discountedPrice: 4500,
    brand: Brand.CaratLane,
    tags: ['silver'],
    thumbnailUrls: [assetUrl("mock.product.silverBand.image1")],
    isNew: false,
    rating: 4,
  },
  {
    id: "prod-001",
    name: "Classic Gold Necklace",
    title: "Classic Gold Necklace",
    description: "Elegant 22K gold necklace with intricate design.",
    productType: ProductType.Necklace,
    givenPrice: 1200,
    discountedPrice: 999,
    brand: Brand.KalyanJewellers,
    tags: ["gold", "necklace", "classic", "22K"],
    isNew: true,
    rating: 5,
    thumbnailUrls: [
      assetUrl("mock.product.prod001GoldNecklace.image1"),
      assetUrl("mock.product.prod001GoldNecklace.image2"),
    ],
  },
  {
    id: "prod-002",
    name: "Diamond Stud Earrings",
    title: "Diamond Stud Earrings",
    description: "Timeless diamond studs set in 18K white gold.",
    productType: ProductType.DiamondStone,
    givenPrice: 800,
    discountedPrice: 749,
    brand: Brand.Tanishq,
    tags: ["diamond", "earrings", "stud", "white-gold"],
    thumbnailUrls: [
      assetUrl("mock.product.prod002DiamondStuds.image1"),
      assetUrl("mock.product.prod002DiamondStuds.image2"),
    ],
  },
  {
    id: "prod-003",
    name: "Silver Charm Bracelet",
    title: "Silver Charm Bracelet",
    description: "Sterling silver bracelet with customizable charms.",
    productType: ProductType.Bracelet,
    givenPrice: 250,
    discountedPrice: 199,
    brand: Brand.KalyanJewellers,
    tags: ["silver", "bracelet", "charms", "sterling"],
    thumbnailUrls: [
      assetUrl("mock.product.prod003CharmBracelet.image1"),
    ],
  },
  {
    id: "prod-004",
    name: "Ruby Ring",
    title: "Ruby Ring",
    description: "Statement ring featuring a natural ruby centerpiece.",
    productType: ProductType.Ring,
    givenPrice: 950,
    discountedPrice: 875,
    brand: Brand.Tanishq,
    tags: ["ruby", "ring", "gemstone", "statement"],
    thumbnailUrls: [
      assetUrl("mock.product.prod004RubyRing.image1"),
      assetUrl("mock.product.prod004RubyRing.image2"),
    ],
  },
  {
    id: "prod-005",
    name: "Ruby Earring",
    title: "Ruby Earring",
    description: "Statement Earring featuring a natural ruby centerpiece.",
    productType: ProductType.Earring,
    givenPrice: 950,
    discountedPrice: 875,
    brand: Brand.Tanishq,
    tags: ["ruby", "ring", "gemstone", "statement"],
    thumbnailUrls: [
      assetUrl("mock.product.prod005RubyEarring.image1"),
      assetUrl("mock.product.prod005RubyEarring.image2"),
    ],
  },
  {
    id: "prod-006",
    name: "Diamond Necklace Gift",
    title: "Diamond Necklace Gift",
    description: "Timeless diamond necklace gift set in 18K white gold.",
    productType: ProductType.Gift,
    givenPrice: 800,
    discountedPrice: 749,
    brand: Brand.CaratLane,
    tags: ["diamond", "earrings", "stud", "white-gold"],
    thumbnailUrls: [
      assetUrl("mock.product.prod006DiamondNecklaceGift.image1"),
      assetUrl("mock.product.prod006DiamondNecklaceGift.image2"),
    ],
  },

  {
    id: "prod-007",
    name: "Gold Necklace",
    title: "Diamond Necklace ",
    description: "Timeless gold necklace set in 18K white gold.",
    productType: ProductType.Gold,
    givenPrice: 800,
    discountedPrice: 749,
    brand: Brand.CaratLane,
    tags: ["diamond", "earrings", "stud", "white-gold"],
    thumbnailUrls: [
      assetUrl("mock.product.prod007GoldNecklace.image1"),
      assetUrl("mock.product.prod007GoldNecklace.image2"),
    ],
  },
];